#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────
# SupaLite setup
# Only generates secrets and starts services.
# All other configuration is done via the web admin panel.
# ─────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

# ── Colors ───────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; }
step()  { echo -e "\n${BOLD}── $* ──${NC}"; }

# ── Dependency check ─────────────────────────────────────────
check_deps() {
    step "检查依赖"
    local missing=()

    if ! command -v docker &>/dev/null; then
        missing+=("docker")
    fi
    if ! docker compose version &>/dev/null 2>&1; then
        if ! command -v docker-compose &>/dev/null; then
            missing+=("docker-compose")
        fi
    fi
    if ! command -v openssl &>/dev/null; then
        missing+=("openssl")
    fi
    if ! command -v curl &>/dev/null; then
        missing+=("curl")
    fi

    if [ ${#missing[@]} -gt 0 ]; then
        err "缺少必要依赖: ${missing[*]}"
        err "请先安装后重试。"
        exit 1
    fi
    ok "docker, docker compose, openssl, curl 已就绪"
}

# ── Generate random secret ───────────────────────────────────
gen_secret() {
    openssl rand -base64 "$1" | tr -d '\n/+=' | head -c "$1"
}

# ── Generate JWT (pure bash + openssl) ───────────────────────
gen_jwt() {
    local payload="$1"
    local secret="$2"

    local header='{"alg":"HS256","typ":"JWT"}'
    local b64_header
    b64_header=$(echo -n "$header" | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')
    local b64_payload
    b64_payload=$(echo -n "$payload" | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')

    local signature
    signature=$(echo -n "${b64_header}.${b64_payload}" \
        | openssl dgst -sha256 -hmac "$secret" -binary \
        | openssl base64 -e -A \
        | tr '+/' '-_' | tr -d '=')

    echo "${b64_header}.${b64_payload}.${signature}"
}

# ══════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════

echo -e "${BOLD}"
echo "  ╔═══════════════════════════════════════╗"
echo "  ║         SupaLite  setup          ║"
echo "  ║   Postgres + PostgREST + GoTrue       ║"
echo "  ╚═══════════════════════════════════════╝"
echo -e "${NC}"

check_deps

# ── Guard: existing .env ─────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
    warn ".env 文件已存在。"
    echo -en "${BOLD}是否覆盖重新生成密钥？(y/N): ${NC}"
    read -r input
    if [[ ! "$input" =~ ^[Yy] ]]; then
        info "保留现有配置，直接启动服务..."
        cd "$SCRIPT_DIR"
        docker compose up -d
        echo ""
        ok "服务已启动！管理面板: ${CYAN}http://localhost:8000/admin/${NC}"
        exit 0
    fi
fi

# ── Validate project path ────────────────────────────────────
# SCRIPT_DIR will be written to .env as HOST_PROJECT_DIR. Docker Compose's
# .env parser doesn't support every special character cleanly, so we
# require the project path to use a safe subset of filesystem characters.
case "$SCRIPT_DIR" in
    *[\"\$\\\`\'\<\>\|\&\;\(\)\{\}\#\!\*\?]*)
        err "项目路径含不安全字符，无法写入 .env: $SCRIPT_DIR"
        err "请把项目移到纯 ASCII / 无特殊字符的路径后重试"
        exit 1
        ;;
    *$'\n'*|*$'\r'*)
        err "项目路径含换行符: $SCRIPT_DIR"
        exit 1
        ;;
esac

# ── 1. Generate all secrets automatically ────────────────────
step "自动生成密钥"

POSTGRES_PASSWORD=$(gen_secret 32)
ok "POSTGRES_PASSWORD (所有 Supabase 规范角色共用此密码)"

JWT_SECRET=$(gen_secret 64)
ok "JWT_SECRET (${#JWT_SECRET} chars)"

ADMIN_TOKEN=$(gen_secret 48)
ok "ADMIN_TOKEN (管理面板访问令牌)"

PG_META_CRYPTO_KEY=$(gen_secret 32)
ok "PG_META_CRYPTO_KEY (Studio 保存凭证的加密密钥)"

COOKIE_SIGNING_KEY=$(gen_secret 32)
ok "COOKIE_SIGNING_KEY (Cookie HMAC 密钥)"

ANON_KEY=$(gen_jwt '{"role":"anon","iss":"SupaLite","iat":1700000000,"exp":4102444800}' "$JWT_SECRET")
ok "ANON_KEY"

SERVICE_ROLE_KEY=$(gen_jwt '{"role":"service_role","iss":"SupaLite","iat":1700000000,"exp":4102444800}' "$JWT_SECRET")
ok "SERVICE_ROLE_KEY"

# ── 2. Write .env with safe defaults ─────────────────────────
step "写入 .env"

cat > "$ENV_FILE" <<EOF
############
# Secrets (auto-generated by setup.sh — $(date +%Y-%m-%d))
############

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ADMIN_TOKEN=${ADMIN_TOKEN}
PG_META_CRYPTO_KEY=${PG_META_CRYPTO_KEY}
COOKIE_SIGNING_KEY=${COOKIE_SIGNING_KEY}

# JWT expiry in seconds (1 hour default)
JWT_EXP=3600

############
# Docker Compose profiles
############
# Comma-separated list of optional services to enable.
#   studio      — Supabase Studio (table editor, SQL editor, auth UI)
#   pgbackrest  — pgBackRest incremental backups (future Phase 6)
# Delete this line (or remove "studio") to run the minimal stack.
COMPOSE_PROFILES=studio

############
# API Keys
############

ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

############
# Networking
############

SITE_URL=http://localhost:3000
API_EXTERNAL_URL=http://localhost:8000

############
# GoTrue / Auth
############

GOTRUE_DISABLE_SIGNUP=false
GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED=true

# SMTP (configure via admin panel)
GOTRUE_SMTP_HOST=
GOTRUE_SMTP_PORT=587
GOTRUE_SMTP_USER=
GOTRUE_SMTP_PASS=
GOTRUE_SMTP_ADMIN_EMAIL=noreply@example.com
GOTRUE_MAILER_AUTOCONFIRM=true

# OAuth — GitHub (configure via admin panel)
GOTRUE_EXTERNAL_GITHUB_ENABLED=false
GOTRUE_EXTERNAL_GITHUB_CLIENT_ID=
GOTRUE_EXTERNAL_GITHUB_SECRET=
GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI=http://localhost:8000/auth/v1/callback

# OAuth — Google (configure via admin panel)
GOTRUE_EXTERNAL_GOOGLE_ENABLED=false
GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID=
GOTRUE_EXTERNAL_GOOGLE_SECRET=
GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI=http://localhost:8000/auth/v1/callback

# OAuth — Apple (configure via admin panel)
GOTRUE_EXTERNAL_APPLE_ENABLED=false
GOTRUE_EXTERNAL_APPLE_CLIENT_ID=
GOTRUE_EXTERNAL_APPLE_SECRET=
GOTRUE_EXTERNAL_APPLE_REDIRECT_URI=http://localhost:8000/auth/v1/callback

############
# Admin
############

SETUP_COMPLETE=false

# Host path of this project directory (used by admin container to run docker compose).
# Double-quoted to tolerate spaces or '(' ')' etc. in paths. Already validated above
# to reject shell metacharacters.
HOST_PROJECT_DIR="${SCRIPT_DIR}"
EOF

chmod 600 "$ENV_FILE"
ok ".env 已生成 (权限 600)"

# ── 3. Pull & start ─────────────────────────────────────────
step "启动服务"

cd "$SCRIPT_DIR"

info "拉取镜像..."
docker compose pull

info "启动容器..."
docker compose up -d

# ── 4. Health check ──────────────────────────────────────────
step "健康检查"

info "等待服务就绪..."
check_endpoint() {
    local name="$1"
    local url="$2"
    local max=30
    local n=0
    while [ $n -lt $max ]; do
        if curl -sf -o /dev/null "$url" 2>/dev/null; then
            ok "$name 就绪"
            return 0
        fi
        sleep 2
        n=$((n + 2))
        echo -n "."
    done
    warn "$name 健康检查超时"
    return 1
}

check_endpoint "Gateway" "http://localhost:8000/health"
check_endpoint "PostgREST" "http://localhost:8000/rest/v1/"
check_endpoint "GoTrue" "http://localhost:8000/auth/v1/health"
check_endpoint "Admin" "http://localhost:8000/admin/"

if false; then
    true
else
    ok "服务检查完成"
fi

# ── 5. Print summary ────────────────────────────────────────
echo ""
echo -e "${BOLD}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║                      安装完成!                                ║${NC}"
echo -e "${BOLD}╠════════════════════════════════════════════════════════════════╣${NC}"
echo -e "${BOLD}║${NC}                                                                ${BOLD}║${NC}"
echo -e "${BOLD}║${NC}  ${GREEN}管理面板 (配置 OAuth / SMTP / 等):${NC}"
echo -e "${BOLD}║${NC}  ${CYAN}http://localhost:8000/admin/${NC}"
echo -e "${BOLD}║${NC}"
echo -e "${BOLD}║${NC}  ${YELLOW}管理令牌 (首次登录使用):${NC}"
echo -e "${BOLD}║${NC}  ${ADMIN_TOKEN}"
echo -e "${BOLD}║${NC}"
echo -e "${BOLD}║${NC}  REST API:   ${CYAN}http://localhost:8000/rest/v1/${NC}"
echo -e "${BOLD}║${NC}  Auth API:   ${CYAN}http://localhost:8000/auth/v1/${NC}"
echo -e "${BOLD}║${NC}  PostgreSQL: ${CYAN}localhost:5432${NC}"
echo -e "${BOLD}║${NC}"
echo -e "${BOLD}║${NC}  ${RED}请妥善保管 .env 文件中的密钥!${NC}"
echo -e "${BOLD}║${NC}                                                                ${BOLD}║${NC}"
echo -e "${BOLD}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""
